[package]
name = "home-control-api"
version = "1.0.0"
authors = ["Andreas Johansson <andreas@stdin.se>"]
publish = false
license = "MIT"

[dependencies]
clap = "2.19.*"
iron = "0.4.*"
lazy_static = "0.1.*"
regex = "0.1.*"
router = "0.4.*"
